import {clamp,lerp,color,hit} from './time';
export type Ctx=CanvasRenderingContext2D;
export type Point=[number,number];
export const font='"Microsoft YaHei", "Noto Sans CJK SC", sans-serif';
export function text(c:Ctx,s:string,x:number,y:number,size=40,fill=color.ink,align:CanvasTextAlign='left',weight=600){c.font=`${weight} ${size}px ${font}`;c.fillStyle=fill;c.textAlign=align;c.textBaseline='middle';c.fillText(s,x,y);}
export function mono(c:Ctx,s:string,x:number,y:number,size=18,fill=color.muted,align:CanvasTextAlign='left'){c.font=`500 ${size}px Consolas,monospace`;c.fillStyle=fill;c.textAlign=align;c.textBaseline='middle';c.fillText(s,x,y);}
export function round(c:Ctx,x:number,y:number,w:number,h:number,r:number,fill:string,stroke?:string){c.beginPath();c.roundRect(x,y,w,h,r);c.fillStyle=fill;c.fill();if(stroke){c.strokeStyle=stroke;c.lineWidth=2;c.stroke();}}
export function tag(c:Ctx,s:string,x:number,y:number,fill=color.mint,fg=color.night,size=24){c.font=`600 ${size}px ${font}`;const w=c.measureText(s).width+34;round(c,x,y-22,w,44,7,fill);text(c,s,x+17,y,size,fg,'left',600);return w;}
export function disk(c:Ctx,x:number,y:number,r:number,fill:string,stroke?:string){c.beginPath();c.arc(x,y,r,0,Math.PI*2);c.fillStyle=fill;c.fill();if(stroke){c.lineWidth=3;c.strokeStyle=stroke;c.stroke();}}
export function link(c:Ctx,a:Point,b:Point,bend:number,p:number,fill=color.mint,width=4,arrow=true){const q=clamp(p);if(q<=0)return;const mid:Point=[(a[0]+b[0])/2,(a[1]+b[1])/2+bend];c.lineWidth=width;c.lineCap='round';c.lineJoin='round';c.strokeStyle=fill;c.beginPath();c.moveTo(...a);let end:Point=a,prior:Point=a;for(let i=1;i<=40;i++){const u=q*i/40;prior=end;end=[(1-u)**2*a[0]+2*(1-u)*u*mid[0]+u*u*b[0],(1-u)**2*a[1]+2*(1-u)*u*mid[1]+u*u*b[1]];c.lineTo(...end);}c.stroke();if(arrow){const angle=Math.atan2(end[1]-prior[1],end[0]-prior[0]);c.save();c.translate(...end);c.rotate(angle);c.fillStyle=fill;c.beginPath();c.moveTo(0,0);c.lineTo(-13,-7);c.lineTo(-10,0);c.lineTo(-13,7);c.closePath();c.fill();c.restore();}}
export function pulse(c:Ctx,a:Point,b:Point,bend:number,p:number,fill=color.orange,r=8){const u=clamp(p),mid:Point=[(a[0]+b[0])/2,(a[1]+b[1])/2+bend];const x=lerp(lerp(a[0],mid[0],u),lerp(mid[0],b[0],u),u),y=lerp(lerp(a[1],mid[1],u),lerp(mid[1],b[1],u),u);c.save();c.shadowColor=fill;c.shadowBlur=20;disk(c,x,y,r,fill);c.restore();}
export function tick(c:Ctx,x:number,y:number,p:number=1,fill=color.mint,size=28){const points:Point[]=[[x-size*.5,y],[x-size*.12,y+size*.4],[x+size*.6,y-size*.45]];c.strokeStyle=fill;c.lineWidth=6;c.lineCap='round';c.lineJoin='round';c.beginPath();c.moveTo(...points[0]!);const q=clamp(p*2);c.lineTo(lerp(points[0]![0],points[1]![0],q),lerp(points[0]![1],points[1]![1],q));if(p>.5){const s=clamp(p*2-1);c.lineTo(lerp(points[1]![0],points[2]![0],s),lerp(points[1]![1],points[2]![1],s));}c.stroke();}
export function cross(c:Ctx,x:number,y:number,size=20,fill=color.red){c.strokeStyle=fill;c.lineWidth=5;c.lineCap='round';c.beginPath();c.moveTo(x-size,y-size);c.lineTo(x+size,y+size);c.moveTo(x-size,y+size);c.lineTo(x+size,y-size);c.stroke();}
export function brackets(c:Ctx,x:number,y:number,w:number,h:number,fill:string){c.strokeStyle=fill;c.lineWidth=4;for(const sx of [-1,1])for(const sy of [-1,1]){const a=x+sx*w/2,b=y+sy*h/2;c.beginPath();c.moveTo(a-sx*26,b);c.lineTo(a,b);c.lineTo(a,b-sy*26);c.stroke();}}
export function token(c:Ctx,s:string,x:number,y:number,w:number,fill=color.paper,fg=color.ink,scale=1){c.save();c.translate(x,y);c.scale(scale,scale);c.shadowColor='rgba(0,17,23,.16)';c.shadowBlur=24;c.shadowOffsetY=14;round(c,-w/2,-56,w,112,15,fill);c.shadowColor='transparent';round(c,-w/2,-53,w,7,4,fill===color.paper?'#fffaf4':'rgba(255,255,255,.3)');text(c,s,0,1,64,fg,'center',600);c.restore();}
export function cursor(c:Ctx,x:number,y:number,click=0){c.save();c.translate(x,y);c.scale(1-click*.14,1-click*.14);c.fillStyle=color.white;c.strokeStyle=color.night;c.lineWidth=3;c.shadowColor='rgba(0,0,0,.2)';c.shadowBlur=9;c.beginPath();c.moveTo(0,0);c.lineTo(7,46);c.lineTo(20,32);c.lineTo(31,53);c.lineTo(40,48);c.lineTo(28,28);c.lineTo(48,25);c.closePath();c.fill();c.stroke();c.restore();}
export function stamp(c:Ctx,s:string,x:number,y:number,t:number,at:number,fill=color.red){const p=hit(t,at,.3);if(p<=0)return;c.save();c.translate(x,y);c.rotate(-.13);c.scale(p,p);c.strokeStyle=fill;c.lineWidth=6;c.strokeRect(-165,-43,330,86);text(c,s,0,0,50,fill,'center',700);c.restore();}
