import * as T from 'three';
export const C={ink:0x061019,cyan:0x65e5ed,gold:0xffc278,white:0xe8f3f6,red:0xff676c,blue:0x4082b8,slate:0x253c4b};
export const clamp=(x:number)=>Math.max(0,Math.min(1,x));
export const ease=(x:number)=>{x=clamp(x);return x*x*x*(x*(x*6-15)+10);};
export const out=(x:number)=>1-Math.pow(1-clamp(x),3);
export const spring=(x:number)=>x<=0?0:x>=1?1:1-Math.exp(-7*x)*Math.cos(10*x);
export const mix=(a:number,b:number,t:number)=>a+(b-a)*t;
export const fract=(n:number)=>n-Math.floor(n);
export const hash=(n:number)=>fract(Math.sin(n*127.1+311.7)*43758.5453);
export const v=(x=0,y=0,z=0)=>new T.Vector3(x,y,z);
export type Actor={root:T.Group,update:(t:number)=>void};
export const metal=(color:number=C.slate,roughness=.24)=>new T.MeshStandardMaterial({color,roughness,metalness:.76});
export const glow=(color:number=C.cyan,opacity=1)=>new T.MeshBasicMaterial({color,transparent:opacity<1,opacity,depthWrite:opacity>=1,toneMapped:false});
export function mesh(g:T.BufferGeometry,m:T.Material,x=0,y=0,z=0){const a=new T.Mesh(g,m);a.position.set(x,y,z);return a;}
export function box(w:number,h:number,d:number,color:number=C.slate,x=0,y=0,z=0){return mesh(new T.BoxGeometry(w,h,d),metal(color),x,y,z);}
export function ball(r:number,color:number=C.cyan,x=0,y=0,z=0){return mesh(new T.SphereGeometry(r,20,14),metal(color,.17),x,y,z);}
export function ring(r:number,color:number=C.cyan,tube=.022){return mesh(new T.TorusGeometry(r,tube,8,112),glow(color));}
export function segment(a:T.Vector3,b:T.Vector3,color:number=C.cyan,r=.022){const delta=b.clone().sub(a),m=mesh(new T.CylinderGeometry(r,r,delta.length(),7),glow(color));m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(v(0,1,0),delta.normalize());return m;}
export function curve(points:T.Vector3[],color:number=C.cyan,r=.022){return mesh(new T.TubeGeometry(new T.CatmullRomCurve3(points),Math.max(24,points.length*12),r,6,false),glow(color));}
export function outline(w:number,h:number,color:number=C.cyan){const p=[v(-w/2,-h/2),v(w/2,-h/2),v(w/2,h/2),v(-w/2,h/2),v(-w/2,-h/2)];return new T.Line(new T.BufferGeometry().setFromPoints(p),new T.LineBasicMaterial({color,transparent:true,opacity:.7}));}
const font='"Noto Sans CJK SC", "Noto Sans SC", "Microsoft YaHei", sans-serif';
export function label(text:string,color='#e8f3f6',size=1,width=1024){const c=document.createElement('canvas');c.width=width;c.height=144;const ctx=c.getContext('2d')!;ctx.font=`500 86px ${font}`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=color;ctx.fillText(text,width/2,75,width-30);const tx=new T.CanvasTexture(c);tx.colorSpace=T.SRGBColorSpace;const mat=new T.SpriteMaterial({map:tx,depthWrite:false,transparent:true,toneMapped:false});const s=new T.Sprite(mat);s.scale.set(size*width/144,size,1);return s;}
let haloTexture:T.CanvasTexture|undefined;
export function halo(color:number=C.cyan,size=3,opacity=.26){if(!haloTexture){const c=document.createElement('canvas');c.width=c.height=128;const q=c.getContext('2d')!,g=q.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'rgba(255,255,255,.8)');g.addColorStop(.12,'rgba(255,255,255,.34)');g.addColorStop(.45,'rgba(255,255,255,.06)');g.addColorStop(1,'rgba(255,255,255,0)');q.fillStyle=g;q.fillRect(0,0,128,128);haloTexture=new T.CanvasTexture(c);}const s=new T.Sprite(new T.SpriteMaterial({map:haloTexture,color,opacity,transparent:true,depthWrite:false,blending:T.AdditiveBlending}));s.scale.setScalar(size);return s;}
export function core(r=1){const g=new T.Group(),sphere=ball(r,C.slate);g.add(sphere);const skin=mesh(new T.IcosahedronGeometry(r*1.024,1),new T.MeshBasicMaterial({color:C.cyan,wireframe:true,transparent:true,opacity:.28}));g.add(skin);for(let i=0;i<3;i++){const tor=ring(r*1.2,C.gold,.023);tor.rotation.set(.35+i*.9,i*.6,.2+i*.8);g.add(tor);}g.add(halo(C.cyan,r*6,.28));return g;}
export function chat(){const g=new T.Group(),body=box(4,2.5,.18,C.slate);g.add(body);const rim=outline(4.12,2.62);rim.position.z=.12;g.add(rim);for(let i=0;i<3;i++){const line=box(2.4-i*.42,.085,.02,C.white,-.2,.57-i*.5,.15);g.add(line);}g.add(curve([v(-1,-1.28,.12),v(-1,-1.84,.12),v(-.25,-1.28,.12)],C.cyan,.04));return g;}
export function codeScreen(){const g=new T.Group();g.add(box(4.7,3.2,.19));const r=outline(4.8,3.3);r.position.z=.15;g.add(r);for(let i=0;i<11;i++){const y=1.18-i*.225;const a=box(.2,.062,.018,C.gold,-2.02,y,.14);g.add(a);let x=-1.6+(i%3)*.18;for(let j=0;j<3;j++){const w=.28+hash(i*13+j)*.58;g.add(box(w,.063,.02,(i+j)%3?C.cyan:C.white,x+w/2,y,.14));x+=w+.12;}}return g;}
export function documentStack(){const g=new T.Group();for(let i=0;i<7;i++){const page=new T.Group();page.add(box(2.3,3.1,.025,0x506570));for(let j=0;j<8;j++)page.add(box(1.65-(j%3)*.2,.065,.012,C.white,-.05,.98-j*.24,.025));page.position.set((i-3)*.25,(i-3)*.1,-i*.15);page.rotation.z=(i-3)*.055;g.add(page);}return g;}
export function chip(){const g=new T.Group();g.add(box(2.4,.4,2.4));const c=box(1.7,.06,1.7,C.gold,0,.25,0);g.add(c);for(let side=0;side<4;side++)for(let i=0;i<12;i++){const p=box(.085,.09,.46,C.white,(i-5.5)*.185,0,1.38);const sub=new T.Group();sub.add(p);sub.rotation.y=side*Math.PI/2;g.add(sub);}for(let i=0;i<6;i++){const t=ring(.26+i*.08,C.cyan,.01);t.rotation.x=Math.PI/2;t.position.y=.3;g.add(t);}return g;}
export function protein(){const g=new T.Group();for(let k=0;k<3;k++){const pts=[];for(let i=0;i<=140;i++){const u=i/140*Math.PI*4.8;pts.push(v(Math.sin(u)*(.68+k*.19)+Math.sin(u*.4)*.8,(i/140-.5)*4.6,Math.cos(u)*(.7+k*.13)+Math.cos(u*.65)*.55));}g.add(curve(pts,k===1?C.gold:C.cyan,.047));}for(let i=0;i<15;i++){let u=i/15*Math.PI*4.8;g.add(ball(.09,i%3?C.white:C.gold,Math.sin(u)*1.1,(i/15-.5)*4.6,Math.cos(u)));}g.rotation.z=-.45;return g;}
export function globe(){const g=new T.Group();g.add(ball(2.2,0x112d3d));const wire=mesh(new T.SphereGeometry(2.215,36,20),new T.MeshBasicMaterial({wireframe:true,color:C.cyan,transparent:true,opacity:.19}));g.add(wire);for(let k=0;k<13;k++){const pts=[];for(let i=0;i<50;i++){const a=i/49*3.2+k*.55,lat=(hash(k)-.5)*2;pts.push(v(2.26*Math.cos(lat)*Math.sin(a),2.26*Math.sin(lat+.09*Math.sin(a*4+k)),2.26*Math.cos(lat)*Math.cos(a)));}g.add(curve(pts,k%4===0?C.gold:C.cyan,.021));}g.add(halo(C.cyan,8,.21));return g;}
export function robot(){const g=new T.Group();g.add(mesh(new T.CylinderGeometry(.8,1,.36,32),metal(),0,-2.3,0));const base=new T.Group();base.position.y=-2.08;g.add(base);const shoulder=ball(.33,C.gold);base.add(shoulder);const upper=box(.4,2,.45,C.slate,0,1,0);base.add(upper);const elbow=new T.Group();elbow.position.y=2;base.add(elbow);elbow.add(ball(.32,C.cyan));elbow.add(box(.33,1.8,.36,C.slate,0,.9,0));const wrist=new T.Group();wrist.position.y=1.8;elbow.add(wrist);wrist.add(ball(.21,C.white));for(const d of [-1,1]){const finger=box(.1,.6,.12,C.gold,d*.22,.32,0);wrist.add(finger);}g.userData.grip=wrist;g.userData.pose=(t:number)=>{base.rotation.z=-.7+.35*Math.sin(t*1.9);elbow.rotation.z=1.7+.28*Math.sin(t*1.9+.9);wrist.rotation.z=-.5-.2*Math.sin(t*1.9);};return g;}
export function bars(count=36){const g=new T.Group();for(let i=0;i<count;i++){const b=box(.16,1,.17,i%6===0?C.gold:C.cyan,(i-(count-1)/2)*.22,0,0);g.add(b);}g.userData.wave=(t:number)=>{g.children.forEach((b,i)=>{const h=.25+1.8*Math.pow(Math.sin(i*.31-t*4.2),2)*(.35+.65*Math.pow(Math.sin(i*.07+t),2));b.scale.y=h;b.position.y=0;});};return g;}
export function particles(count=200){const ar=new Float32Array(count*3);for(let i=0;i<count;i++){ar[i*3]=(hash(i*3)-.5)*38;ar[i*3+1]=(hash(i*3+1)-.5)*22;ar[i*3+2]=(hash(i*3+2)-.5)*28;}const geo=new T.BufferGeometry();geo.setAttribute('position',new T.BufferAttribute(ar,3));return new T.Points(geo,new T.PointsMaterial({color:C.cyan,size:.032,transparent:true,opacity:.32,depthWrite:false}));}
export function flow(count:number,at:(i:number,t:number)=>T.Vector3,color:number=C.cyan,r=.065){const im=new T.InstancedMesh(new T.SphereGeometry(r,8,6),glow(color),count),dummy=new T.Object3D();im.instanceMatrix.setUsage(T.DynamicDrawUsage);return {mesh:im,update(t:number){for(let i=0;i<count;i++){dummy.position.copy(at(i,t));dummy.scale.setScalar(.5+hash(i)*.9);dummy.updateMatrix();im.setMatrixAt(i,dummy.matrix);}im.instanceMatrix.needsUpdate=true;}};}
export function disposeTree(root:T.Object3D){const geometries=new Set<T.BufferGeometry>(),materials=new Set<T.Material>(),textures=new Set<T.Texture>();root.traverse(o=>{const a=o as T.Mesh;if(a.geometry)geometries.add(a.geometry);if(a.material){const ms=Array.isArray(a.material)?a.material:[a.material];ms.forEach(m=>{materials.add(m);const x=m as T.MeshStandardMaterial;if(x.map)textures.add(x.map);});}});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());haloTexture=undefined;}
