import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import sharp from 'sharp';
const root=path.resolve('projects/the-learning-machine');
const id=process.argv[2];if(!id||!/^[a-f0-9-]{36}$/.test(id))throw new Error('Pass the successful R3 render UUID.');
const render=path.join(root,'exports/renders',id),input=path.join(render,'film.mp4'),reportPath=path.join(render,'verification/verification.json');
const verification=JSON.parse(fs.readFileSync(reportPath,'utf8'));
if(verification.status!=='passed'||verification.media?.fullDecode!=='passed'||verification.media?.decodedFrames!==4680||verification.version?.matches!==true)throw new Error('R3 full decode/version checks did not pass.');
const sha=f=>createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const movieHash=sha(input);if(movieHash!==verification.sha256)throw new Error('Movie hash does not match verification.');
const directory=path.join(root,'exports/delivery/r3');fs.mkdirSync(directory,{recursive:true});
const movie=path.join(directory,'AI-seventy-years-R3-1080p.mp4');
if(fs.existsSync(movie)&&sha(movie)!==movieHash)throw new Error('Different R3 deliverable exists; refusing silent overwrite.');
fs.copyFileSync(input,movie);
fs.copyFileSync(reportPath,path.join(directory,'verification.json'));
const renderReport=input+'.render.json';if(fs.existsSync(renderReport))fs.copyFileSync(renderReport,movie+'.render.json');
fs.copyFileSync(path.join(root,'public/r3-captions.srt'),path.join(directory,'captions.zh-CN.srt'));
await sharp(path.join(root,'public/poster.svg')).resize(1920,1080,{fit:'inside'}).jpeg({quality:94}).toFile(path.join(directory,'cover.jpg'));
const credit="'Emergent' by Scott Buckley - released under CC-BY 4.0. www.scottbuckley.com.au";
fs.writeFileSync(path.join(directory,'配乐署名与发布说明.txt'),`不是突然变聪明｜AI 的七十年 · R3\n\n配乐署名（发布视频时请保留在简介）：\n${credit}\n\n曲目来源：https://www.scottbuckley.com.au/library/emergent/\n许可证：https://creativecommons.org/licenses/by/4.0/\n本片对配乐做节选、交叉淡化和混音。配乐不是本项目原创曲目。\n\n旁白为AI合成普通话 zh-CN-YunyangNeural，不是任何真人声音克隆。\n画面、模型、原始纹理、动画、镜头与叙事为本项目R3原创制作。\n原理、笔迹、模型、棋局、权重和概率均为教学示意，不是具体模型实验结果或历史比赛复刻。\n完整可编辑工程仍在Frame Studio的the-learning-machine项目，当前入口r3/scene.ts。\n`);
const chapters=[[0,'开篇'],[10.982,'规则与例外'],[29.11,'从样本学习'],[52.972,'三者合流'],[71.908,'决策'],[88.804,'注意力'],[102.82,'预测与协作'],[132.288,'核验'],[143.672,'结尾']];
fs.writeFileSync(path.join(directory,'播放.html'),`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>不是突然变聪明｜AI 的七十年 · R3</title><style>*{box-sizing:border-box}body{margin:0;background:#0b1d26;color:#dce8dc;font-family:system-ui,'Microsoft YaHei',sans-serif}main{max-width:1180px;margin:40px auto;padding:0 24px}h1{font-weight:600;letter-spacing:.02em}p{color:#adc2b3;line-height:1.8}video{display:block;width:100%;background:#07151d;border-radius:10px}nav{display:flex;gap:9px;flex-wrap:wrap;margin:20px 0}button{border:1px solid #426759;background:#143b37;color:#e3ecdf;padding:9px 14px;border-radius:6px;cursor:pointer}small{display:block;line-height:1.8;color:#91ad9e}a{color:#b4d6c1}</style><main><h1>不是突然变聪明</h1><p>AI 的七十年 · R3 · 2分36秒 · 1920×1080 / 30fps</p><video controls playsinline preload="metadata" poster="cover.jpg" src="AI-seventy-years-R3-1080p.mp4"></video><nav>${chapters.map(([at,title])=>`<button data-time="${at}">${title}</button>`).join('')}</nav><small>${credit}<br>音乐已剪辑与混音；发布时保留配乐署名。中文旁白为AI合成。<br><a href="captions.zh-CN.srt">中文字幕</a> · <a href="配乐署名与发布说明.txt">配乐授权与发布说明</a></small></main><script>const v=document.querySelector('video');for(const b of document.querySelectorAll('button'))b.addEventListener('click',()=>{v.currentTime=Number(b.dataset.time);v.play().catch(()=>{});});</script></html>`);
const stream=verification.media.probe.streams.find(s=>s.codec_type==='video'),audio=verification.media.probe.streams.find(s=>s.codec_type==='audio');
const delivery={version:'R3',title:'不是突然变聪明｜AI 的七十年',createdAt:new Date().toISOString(),directory,movie,player:path.join(directory,'播放.html'),subtitles:path.join(directory,'captions.zh-CN.srt'),cover:path.join(directory,'cover.jpg'),renderId:id,sha256:movieHash,bytes:fs.statSync(movie).size,duration:156,width:stream.width,height:stream.height,fps:stream.avg_frame_rate,decodedFrames:verification.media.decodedFrames,sourceFingerprint:verification.version.recorded,sourceMatches:verification.version.matches,media:{fullDecode:verification.media.fullDecode,audioCodec:audio.codec_name,sampleRate:audio.sample_rate,channels:audio.channels,integratedLufs:verification.media.audio.integratedLufs,truePeakDb:verification.media.audio.truePeakDb},music:{title:'Emergent',artist:'Scott Buckley',license:'CC BY 4.0',credit,edited:true},review:{visual:'selected full-film frames and opening sequence inspected; see records/r3-review.md',listening:'not_run: inline audio returned only metadata/link',technicalPlayback:'R3 live output, first-half 78 seconds, independent tracks, pause/reverse/2x, frame reconstruction passed'},engineeringReport:'records/r3-validation.json',browserReport:'records/r3-e2e.json',verification:reportPath};
fs.writeFileSync(path.join(directory,'delivery.json'),JSON.stringify(delivery,null,2));fs.writeFileSync(path.join(root,'records/r3-delivery.json'),JSON.stringify(delivery,null,2));
console.log(JSON.stringify(delivery,null,2));
